services:

  # === MONGODB REPLICA SET ===
  # 3 nodi: 1 primary + 2 secondary
  mongodb-primary:
    image: mongo:8.2
    container_name: mongodb-primary
    hostname: mongodb-primary
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-primary-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - masd-network

  mongodb-secondary1:
    image: mongo:8.2
    container_name: mongodb-secondary1
    hostname: mongodb-secondary1
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-secondary1-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - masd-network

  mongodb-secondary2:
    image: mongo:8.2
    container_name: mongodb-secondary2
    hostname: mongodb-secondary2
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-secondary2-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - masd-network

  # Inizializzazione del replica set
  mongodb-init:
    image: mongo:8.2
    container_name: mongodb-init
    depends_on:
      mongodb-primary:
        condition: service_healthy
      mongodb-secondary1:
        condition: service_healthy
      mongodb-secondary2:
        condition: service_healthy
    # Il comando:
    #   - Inizializza il replica set con 1 primary e 2 secondary
    #   - Attende che tutti i membri del replica set siano pronti (stato 1 o 2)
    # Termina con successo quando il replica set è pronto
    command: >
      bash -c "
      mongosh --host mongodb-primary:27017 --eval '
      rs.initiate({
        _id: \"rs0\",
        members: [
          { _id: 0, host: \"mongodb-primary:27017\", priority: 2 },
          { _id: 1, host: \"mongodb-secondary1:27017\", priority: 1 },
          { _id: 2, host: \"mongodb-secondary2:27017\", priority: 1 }
        ]
      })' &&
      echo 'Replica set initiated, waiting for members to be ready...' &&
      until mongosh --host mongodb-primary:27017 --quiet --eval '
        const status = rs.status();
        const ready = status.members.every(m => m.state === 1 || m.state === 2);
        quit(ready ? 0 : 1);
      '; do
        sleep 2;
      done &&
      echo 'Replica set is ready!'
      "
    networks:
      - masd-network

  # === MONGODB UI ===
  # Per avviare: docker-compose --profile mongo-ui up -d
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    profiles:
      - mongo-ui
    depends_on:
      mongodb-primary:
        condition: service_healthy
      mongodb-secondary1:
        condition: service_healthy
      mongodb-secondary2:
        condition: service_healthy
      mongodb-init:
        condition: service_completed_successfully
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}&readPreference=${MONGO_READ_PREFERENCE}
      ME_CONFIG_BASICAUTH: false
    networks:
      - masd-network
